apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bpm-logs-pvc
  namespace: bpm-scrape
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path  # k3s default storage class
